parameters = {'Au': {'bond':      -13,
                     'corner':   -404,
                     'edge':     -301,
                     'terrace':  -200,
                     'interior':    0,
                     'layer':       0},

              'Ag': {'bond':       -1,
                     'corner':   -361,
                     'edge':     -289,
                     'terrace':  -163,
                     'interior':    0,
                     'layer':       0},

              'Cu': {'bond':      -26,
                     'corner':     95,
                     'edge':      147,
                     'terrace':   183,
                     'interior':    0,
                     'layer':       0},

              'Zn': {'bond':     -160,
                     'corner':   -251,
                     'edge':     -205,
                     'terrace':   -90,
                     'interior':    0,
                     'layer':    -105}}
